apiVersion: apps/v1
kind: Deployment
metadata:
  name: milkyway-sample
  labels:
    app: milkyway-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milkyway-sample
  template:
    metadata:
      labels:
        app: milkyway-sample
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: milkyway-sample
          image: "buzzfrog/metrics-prometheus:0.2"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30